version: "3"
services:
  nautobot:
    build:
      context: "../"
      dockerfile: "development/Dockerfile"
      args:
        python_ver: ${PYTHON_VER}
    image: "nautobot-plugin-device-lifecycle-mgmt/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    command: "nautobot-server runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - "./dev.env"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../nautobot_device_lifecycle_mgmt:/source/nautobot_device_lifecycle_mgmt"
    tty: true
  worker:
    build:
      context: "../"
      dockerfile: "development/Dockerfile"
      args:
        nautobot_ver: ${NAUTOBOT_VER}
        python_ver: ${PYTHON_VER}
    image: "nautobot-plugin-device-lifecycle-mgmt/nautobot:${NAUTOBOT_VER}-py${PYTHON_VER}"
    entrypoint: "nautobot-server rqworker"
    depends_on:
      - "nautobot"
    env_file:
      - "./dev.env"
    volumes:
      - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
      - "../nautobot_device_lifecycle_mgmt:/source/nautobot_device_lifecycle_mgmt"
    tty: true
  postgres:
    image: "postgres:13"
    env_file: "dev.env"
    volumes:
      - "pgdata_nautobot_device_lifecycle_mgmt:/var/lib/postgresql/data"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"  ## $$ because of docker-compose
    env_file: "./dev.env"
volumes:
  pgdata_nautobot_device_lifecycle_mgmt:  # yamllint disable-line rule:empty-values
