name: "All CI related tasks"

on: ["push", "pull_request"]

jobs:
  linting_unit_testing:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install and configure Poetry"
        uses: "snok/install-poetry@v1.1.1"
        with:
          virtualenvs-create: false
      - name: "Install Python packages"
        run: "poetry install"
      - name: "Build Testing Container"
        run: "PYTHON_VER=${{ matrix.python-version }} invoke build"
      - name: "Run All Tests"
        run: "PYTHON_VER=${{ matrix.python-version }} invoke tests"
      - name: Publish package if tagged
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: JRubics/poetry-publish@v1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
